backend:
  name: git-gateway
  branch: master
  
publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    format: "json"
    sort: "published_at:desc"
    folder: "assets/content/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Image",
          name: "featuredImage",
          widget: "image",
          required: false,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "excerpt", widget: "text" }
      - {
          label: "Published At",
          name: publishedAt,
          widget: date,
          format: "Do MMM YYYY",
        }
      - {
          label: "SEO Description",
          name: "seoDescription",
          widget: "text",
          required: false,
        }
      - {
          label: "SEO Meta Image",
          name: "seoMetaImage",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "about"
    label: "About"
    format: "json"
    sort: "published_at:desc"
    folder: "assets/content/about"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "text" }
      - {
          label: "Published At",
          name: publishedAt,
          widget: date,
          format: "Do MMM YYYY",
        }
      - {
          label: "SEO Description",
          name: "seoDescription",
          widget: "text",
          required: false,
        }
      - {
          label: "SEO Meta Image",
          name: "seoMetaImage",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "home"
    label: "Home"
    format: "json"
    sort: "published_at:desc"
    folder: "assets/content/home"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "excerpt", widget: "text" }
      - {
          label: "Published At",
          name: publishedAt,
          widget: date,
          format: "Do MMM YYYY",
        }
      - {
          label: "SEO Description",
          name: "seoDescription",
          widget: "text",
          required: false,
        }
      - {
          label: "SEO Meta Image",
          name: "seoMetaImage",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
